# -*- coding: utf-8 -*-
"""src_dashboard1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EerywNoY_lOq_bPvyWJzDdRBye6fv_00

**Building dashboard based on the Financial metrices below:**

Summary Table for Board Meetings

Financial Metric | Strategic Importance | Red Flag for Board

(1) Days Cash on Hand | Operational continuity | Less than 180 days.

(2) Investment Income | Diversifying revenue beyond donations | Decline in market value of holdings.

(3) Deferred Income | Tracking grants not yet utilized. | High deferred income with low program output.

(4) Receivables | Ensuring government grants are paid on time. | Large "aged" receivables (>90 days).

# COMBINED Python Scripts
"""

#pip install streamlit pandas plotly fpdf kaleido

import streamlit as st
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from fpdf import FPDF
import io

# --- 1. CONFIGURATION & MOCK DATA ---
st.set_page_config(page_title="SRC Board Suite", layout="wide")

# Static data from 2024 Financial Highlights
TOTAL_ASSETS = 138871
CASH_EQUIVALENTS = 74698
BASE_UNRESTRICTED = 130019
BASE_BUDGET = 35000

# --- 2. SIDEBAR CONTROLS (SCENARIO TOOLS) ---
st.sidebar.header("🛠️ Scenario Planner")
donation_change = st.sidebar.slider("Donation Change (%)", -50, 50, 0)
extra_spend = st.sidebar.number_input("Emergency Spend (SGD '000)", 0, 50000, 0)
inflation = st.sidebar.slider("Operational Inflation (%)", 0, 10, 3)

# --- 3. LOGIC ENGINE ---
adj_budget = (BASE_BUDGET * (1 + inflation/100)) + extra_spend
rev_impact = (BASE_BUDGET * 0.7) * (donation_change / 100)
final_reserve = BASE_UNRESTRICTED + rev_impact - extra_spend
final_ratio = final_reserve / adj_budget

# --- 4. DASHBOARD UI ---
st.title("📊 Singapore Red Cross: Strategic Board Suite")
st.markdown("### Interactive Financial Position & Stress Test")

# KPI Row
c1, c2, c3, c4 = st.columns(4)
c1.metric("Total Assets", f"${TOTAL_ASSETS:,}k")
c2.metric("Cash Position", f"${CASH_EQUIVALENTS:,}k")
c3.metric("Adj. Annual Budget", f"${adj_budget:,.0f}k")
status_color = "normal" if final_ratio > 3 else "inverse"
c4.metric("Reserve Ratio", f"{final_ratio:.2f} Yrs", f"{final_ratio-3.7:.1f} vs 2024", delta_color=status_color)

st.divider()

# Visualization Row
left_chart, right_chart = st.columns(2)

with left_chart:
    st.subheader("Fund Composition")
    df_funds = pd.DataFrame({
        "Category": ["Unrestricted", "Restricted", "Endowment"],
        "Value": [final_reserve, 4520, 4332]
    })
    fig_pie = px.pie(df_funds, values='Value', names='Category', hole=0.4, color_discrete_sequence=px.colors.sequential.Reds_r)
    st.plotly_chart(fig_pie, width='stretch')

with right_chart:
    st.subheader("5-Year Sustainability Projection")
    years = [2024, 2025, 2026, 2027, 2028]
    res_path = [BASE_UNRESTRICTED]
    for i in range(4):
        res_path.append(max(0, res_path[-1] + rev_impact - (adj_budget - BASE_BUDGET)))

    fig_line = go.Figure()
    fig_line.add_trace(go.Scatter(x=years, y=res_path, fill='tozeroy', line_color='red' if donation_change < 0 else 'green'))
    fig_line.update_layout(height=400)
    st.plotly_chart(fig_line, width='stretch')

# --- 5. PDF EXPORT LOGIC ---
def generate_pdf(reserve, ratio, fig_obj):
    pdf = FPDF()
    pdf.add_page()
    pdf.set_font("Arial", 'B', 16)
    pdf.cell(200, 10, txt="SRC Strategic Simulation Report", ln=True, align='C')
    pdf.ln(10)
    pdf.set_font("Arial", size=12)
    pdf.cell(200, 10, txt=f"Projected Reserve: SGD {reserve:,.0f}k", ln=True)
    pdf.cell(200, 10, txt=f"Reserve Ratio: {ratio:.2f} Years", ln=True)

    # Chart embedding
    img_bytes = fig_obj.to_image(format="png")
    img_path = "temp_report_chart.png"
    with open(img_path, "wb") as f:
        f.write(img_bytes)
    pdf.image(img_path, x=10, y=60, w=180)
    return pdf.output(dest='S').encode('latin-1')

st.divider()
if st.button("📥 Export Current Scenario to PDF"):
    pdf_bytes = generate_pdf(final_reserve, final_ratio, fig_line)
    st.download_button("Click here to Download PDF", data=pdf_bytes, file_name="SRC_Board_Report.pdf")